Ndef feature
ElectronicCats/ElectronicCats-PN7150 pull request #52
Opened 2023-08-02 15:58 UTC by DeimosHall

This is a beta version of the NDEF examples, they will be improved in the `refactor` branch.

Examples:

- NDEF Send (Emulate NDEF record)
- NDEF Receive (Read NDEF record)

2023-08-02 16:37 UTC, sabas1080 requested changes

2023-08-02 16:37 UTC, sabas1080 commented on examples/NDEFReceive/NDEFReceive.ino
> +        // Serial.println(ndef_helper_UriHead(NdefRecord.recordPayload[0]), &NdefRecord.recordPayload[1]);
No dejar comentarios innecesarios

2023-08-02 16:37 UTC, sabas1080 commented on examples/NDEFReceive/NDEFReceive.ino
> +        // Serial.println(NdefRecord.recordPayloadSize);
Validar si estos comentarios son necesarios o estos prints

2023-08-02 16:37 UTC, sabas1080 commented on examples/NDEFReceive/NDEFReceive.ino
> +        // Serial.println(NdefRecord.recordPayload, NdefRecord.recordPayloadSize);
Validar si estos comentarios son necesarios o estos prints

2023-08-02 16:37 UTC, sabas1080 commented on examples/NDEFSend/NDEFSend.ino
> +//                              'H', 'e', 'l', 'l', 'o'};  // Message Payload
Validar si estos comentarios son necesarios o sirve como documentacion agregar comentarios extras

2023-08-02 16:37 UTC, sabas1080 commented on src/Electroniccats_PN7150.cpp
> +// #include "T4T_NDEF_emu.h"
Si ya no se van a utilizar remover definitivamente

2023-08-02 16:37 UTC, sabas1080 commented on src/Electroniccats_PN7150.cpp
> +   // (void)writeData(NCIStartDiscovery, NCIStartDiscovery_length);
Si después de las pruebas con otros tipos de funcionamiento sigue funcionando eliminar

2023-08-02 16:37 UTC, sabas1080 commented on src/Electroniccats_PN7150.cpp
>                  //NxpNci_HostTransceive(NCIStopDiscovery, sizeof(NCIStopDiscovery), Answer, sizeof(Answer), &AnswerSize);
Si después de las pruebas con otros tipos de funcionamiento sigue funcionando eliminar

2023-08-02 16:37 UTC, sabas1080 commented on src/Electroniccats_PN7150.cpp
> +                    //(void)writeData(rxBuffer, rxMessageLength);
Si después de las pruebas con otros tipos de funcionamiento sigue funcionando eliminar

2023-08-02 16:37 UTC, sabas1080 commented on src/Electroniccats_PN7150.h
>  //#include "RW_NDEF.h"
Eliminar includes innecesarios

2023-08-02 16:37 UTC, sabas1080 commented on src/Electroniccats_PN7150.h
> +// #define DEBUG3
tal vez sea  bueno redefinir DEBUG, DEBUG2, DEBUG3

2023-08-31 19:13 UTC, sabas1080 requested changes

2023-08-31 19:13 UTC, sabas1080 commented on examples/ISO14443-3A_read_block/ISO14443-3A_read_block.ino
> +  nfc.configMode(mode);
El uso de la variable mode ya no debería ser usado o si??

2023-08-31 19:13 UTC, sabas1080 commented on examples/NDEFRead/NDEFRead.ino
> + *
Agregar tu autoria

2023-08-31 19:13 UTC, sabas1080 commented on src/Electroniccats_PN7150.h
> + *        Andres Sabas - Electronic Cats - electroniccats.com
Agregar tu autoria

2023-08-31 19:13 UTC, sabas1080 commented on src/Electroniccats_PN7150.h
> +// #define DEBGU2
los DEBUG siguen activos??

2023-08-31 19:33 UTC, DeimosHall commented on examples/ISO14443-3A_read_block/ISO14443-3A_read_block.ino
> +  nfc.configMode(mode);
Es correcto, lo actualizaré

2023-08-31 19:33 UTC, DeimosHall commented on src/Electroniccats_PN7150.h
> +// #define DEBGU2
Los DEBUG solo se activan cuando se trabaja en la biblioteca, pero no afectan al usuario si se quedan comentados

2023-08-31 19:34 UTC, DeimosHall commented on src/Electroniccats_PN7150.h
> + *        Andres Sabas - Electronic Cats - electroniccats.com
Ok

2023-08-31 20:56 UTC, REGIOIGER approved these changes
No comments, looks good

2023-08-31 23:20 UTC, sabas1080 approved these changes

2023-09-01 06:18 UTC, merged