Pn7150/60
ElectronicCats/ElectronicCats-PN7150 pull request #62
Opened 2024-12-23 17:47 UTC by REGIOIGER

Arduino library for NFC chips PN7150 and PN7160 with dynamic configuration and easy integration.

2024-12-23 17:48 UTC, sabas1080 commented
@REGIOIGER hacer que pase el precommit porfa

2024-12-24 17:08 UTC, DeimosHall requested changes

2024-12-24 17:40 UTC, REGIOIGER commented on src/Electroniccats_PN7150.h
> +                        uint8_t chipModel, TwoWire *wire = &Wire);
Ok, según yo así es como está

2024-12-24 17:54 UTC, DeimosHall commented on src/Electroniccats_PN7150.h
> +                        uint8_t chipModel, TwoWire *wire = &Wire);
Noup, el último es el de I2C, tiene su valor por defecto y nosotros nunca lo modificamos en los ejemplos pero eso no significa que algún usuario no lo haya hecho

2024-12-27 16:57 UTC, DeimosHall approved these changes

2024-12-30 21:53 UTC, xpeqex commented
Everything is working fine except for the **_ISO15693_write_block_** example, which is not able to write/overwrite to cards/tags using this protocol.

Tested using a BomberCat

2025-02-18 22:20 UTC, sabas1080 commented
#65 #64

2025-04-14 19:03 UTC, sabas1080 reviewed
En general 
- Se deben unificar los ejemplos con las funciones o defines agregados
- Considero se esta duplicando la definicion del chip en el define y en el contructor, para mi deberia ser uno solo, ademas la funcion modelchip no vi en que ejemplo se utilice

2025-04-14 19:03 UTC, sabas1080 commented on examples/NDEFSendRawMessage/NDEFSendRawMessage.ino
> +Electroniccats_PN7150 nfc(PN7150_IRQ, PN7150_VEN, PN7150_ADDR);
Falta agregar los define de los ultimos ejemplo donde se especifica el chip

2025-04-14 19:06 UTC, sabas1080 commented on examples/DetectTagsPN7160/DetectTagsPN7160.ino
> +/**
Este ejemplo se deberia unificar con DetectTags.ino

2025-04-16 22:07 UTC, REGIOIGER commented on examples/DetectTagsPN7160/DetectTagsPN7160.ino
> +/**
Fue eliminado y se dejó solo DetectTags.ino con el parametro del chip explicito.

2025-04-16 22:09 UTC, REGIOIGER commented on examples/ISO14443-3A_write_block/ISO14443-3A_write_block.ino
> +
Se quitó el define y se pasa el chip como parametro en el constructor, en caso de que se necesite conocer el chip se hace uso de getChipModel()

2025-04-24 19:21 UTC, merged